apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
  namespace: app
spec:
  ports:
  - port: 8000
  selector:
    app: redis-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: python:3.11-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install redis flask && \
          cat > /app.py << 'PY'
          from flask import Flask
          import redis
          app = Flask(__name__)
          r = redis.Redis(host='redis.infra.svc.cluster.local', port=6379, decode_responses=True)
          @app.route('/set/<key>/<value>')
          def set_key(key, value):
              r.set(key, value)
              return f"SET {key} = {value}"
          @app.route('/get/<key>')
          def get_key(key):
              return r.get(key) or 'NOT FOUND'
          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=8000)
          PY
          python /app.py
        ports:
        - containerPort: 8000
